// Generated by CoffeeScript 1.12.4
(function() {
  var express, router;

  express = require('express');

  router = express.Router();


  /* GET users listing. */

  router.get('/', function(req, res, next) {
    res.send('respond with a resource');
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=users.js.map
